Models/ErrorViewModel.cs
namespace EventManagement_CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Event.cs
using System;
using System.Collections.Generic;

namespace EventManagement_CRUD.Models
{
    public class Event
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string Organizer { get; set; }
        public List<Ticket> Tickets { get; set; }
    }
}

Models/Ticket.cs
namespace EventManagement_CRUD.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public double Price { get; set; }
        public int EventId { get; set; }

        public Event Event { get; set; }

    }
}

Controllers/EventController.cs
using EventManagement_CRUD.Data;
using EventManagement_CRUD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;

namespace EventManagement_CRUD.Controllers
{
    public class EventController : Controller
    {
        DataContext _context;
        public EventController(DataContext context)
        {
            _context = context;
        }
        public ActionResult Index()
        {
            
            return View();
        }
        
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
     
        public IActionResult Create(string Id, string Name,string Description,string StartDate,string EndDate,string Organizer)
        {
            
            var events = new Event()
            {
                Name = Name,    
                Description = Description,
                StartDate = Convert.ToDateTime(StartDate),
                EndDate = Convert.ToDateTime(EndDate),
                Organizer = Organizer
            };
            try
            {
            
                if (events != null)
                {
                    _context.Events.Add(events);
                    _context.SaveChanges();
                    return Json("success");
                }
                else
                    return Json("failed");

            }
            catch (Exception ex)
            { return Json(ex.Message); }

        }
        
     
    }
}

Controllers/HomeController.cs
using EventManagement_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EventManagement_CRUD.Controllers
{
    public class HomeController : Controller
    {
  
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventManagement_CRUD.Data;
using EventManagement_CRUD.Models;

namespace EventManagement_CRUD.Controllers
{
    public class TicketsController : Controller
    {
        private readonly DataContext _context;

        public TicketsController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Tickets.Include(t => t.Event);
            return View(await dataContext.ToListAsync());
        }



        public IActionResult AddOrEdit(int id)
        {
            if (id == 0 || id == null)
            {
                ViewData["EventId"] = new SelectList(_context.Events, "Id", "Name");
                return View();
            }
            else
            {
                var data = _context.Tickets.Where(x => x.Id == id).FirstOrDefault();
                ViewData["EventId"] = new SelectList(_context.Events, "Id", "Name");
                return View(data);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("Id,Number,Price,EventId")] Ticket ticket)
        {
            if (id != null && id != 0)
            {
                var updateticket = await _context.Tickets.Where(x => x.Id == id).FirstOrDefaultAsync();
                if (updateticket != null)
                {
                    updateticket.Number = ticket.Number;
                    updateticket.Price = ticket.Price;
                    _context.Tickets.Update(updateticket);
                    await _context.SaveChangesAsync();
                }

            }
            else
            {
                if (ModelState.IsValid)
                {
                    _context.Add(ticket);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));


                }
            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _context.Tickets
                .Include(t => t.Event)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // POST: Tickets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ticket = await _context.Tickets.FindAsync(id);
            _context.Tickets.Remove(ticket);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TicketExists(int id)
        {
            return _context.Tickets.Any(e => e.Id == id);
        }
    }
}

Views/Event/Create.cshtml
@model EventManagement_CRUD.Models.Event

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Create Event</h4>
<hr />


<div class="row">
    <div class="col-md-6">
        <form>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="row">

                <div class="form-group col-md-6">
                    <label asp-for="StartDate" class="control-label"></label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>

                </div>
                <div class="form-group col-md-6">
                    <label asp-for="EndDate" class="control-label"></label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Organizer" class="control-label"></label>
                <input asp-for="Organizer" class="form-control" />
                <span asp-validation-for="Organizer" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="button" id="btnsave" value="Create" class="btn btn-primary" />
            </div>

        </form>

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}



<script type="text/javascript">
    $(document).ready(function () {
     
        $("body").on("click", "#btnsave", function () {
           debugger;
           var Id = $("#Id").val();
           var Name= $("#Name").val();
           var Description=$("#Description").val();
           var StartDate=$("#StartDate").val();
           var EndDate=$("#EndDate").val();
           var Organizer=$("#Organizer").val();


           $.ajax({
               type: "POST",
               url: "/Event/Create",
             data: {Id:Id,Name:Name,Description:Description,StartDate: StartDate,EndDate:EndDate,Organizer:Organizer},
                 success: function (r) {
                   alert("Save successfully..!")
                   clear();
               },
               error: function (r) {
                   alert('Failed ' + r);
               }
           });
       });
    });


    function clear()
    {
           $("#Name").val('');
           $("#Description").val('');
           $("#StartDate").val('');
           $("#EndDate").val('');
           $("#Organizer").val('');


    }
</script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventManagement_CRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventManagement_CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Create">Event</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickets" asp-action="Index">Ticket</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EventManagement_CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Tickets/AddOrEdit.cshtml
@model EventManagement_CRUD.Models.Ticket

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Number" class="control-label"></label>
                <input asp-for="Number" class="form-control" />
                <span asp-validation-for="Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Event" class="control-label"></label>
                <select asp-for="EventId" class ="form-control" asp-items="ViewBag.EventId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tickets/Delete.cshtml
@model EventManagement_CRUD.Models.Ticket

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Event.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Tickets/Index.cshtml
@model IEnumerable<EventManagement_CRUD.Models.Ticket>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <a asp-action="AddOrEdit">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Number)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Name)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>